### ISSUE TITLE
Additional Karyotypes for Plots

### ISSUE THREAD

**Issue by mkinnaman** [caravagnalab/CNAqc#11]
Hi!

Im interested in using this tool for the figures it creates, specifically with the circular plots comparing samples karyotypes. Is there anyway to add additional karyotypes that are outside of the standard output: 1:1, 1:0, 0:0, 2:0, 2:1, 2:2? I have some focal amplifications that would be nice to show on one sample not present in another.

Thanks!
Michael

**Comment by caravagn** [comment]
Mmmm can you paste here the kind of plot you have NOW and the one you would like? Technically CNAqc plots all the karyotypes, the only difference is that the ones that are common (1:1, 1:0, 0:0, 2:0, 2:1, 2:2) get coloured, the others do not.

Isn't maybe the case that your focal amplifications are too small to see?  

As a second option, did you try to set higher values for `max_Y_height`? See  https://caravagnalab.github.io/CNAqc/reference/plot_segments.html

**Comment by caravagn** [comment]
Can I close this? @mkinnaman

**Comment by mkinnaman** [comment]
Yes Thank you!
