### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by abcoxyzide** [caravagnalab/CNAqc#20]
https://github.com/caravagnalab/CNAqc/blob/61fab68ac5a639be4b242d99309a19405d1c15a5/R/peak_detector.R#L101-L110

line 107 should be FALSE instead of TRUE, because you want to keep the max count bin?

**Comment by caravagn** [comment]
I think so, will check it asap.

**Comment by Militeee** [comment]
Yea had a look at it, probably a typo, this does not update discarded so all(xy_peaks$discarded) stays TRUE.
Fixed
