### ISSUE TITLE
Low purity but high VAF

### ISSUE THREAD

**Issue by yavorska** [caravagnalab/CNAqc#26]
Hi there, 

We were hoping to use CNAqc to detect errors in some of our purity estimates (particularly for low TMB cases). We've found a few samples where analyze_peaks() passes with a low estimated purity (~0.2). 

However, based on the VAF plot this seems unlikely (there's a clear peak close to 0.5 in diploid regions suggesting a much higher purity). 

Are there any settings that could be modified to change this behaviour? I've tried using the "rightmost" method but that seems to cause pretty much every estimate to fail.

Thank you!

<img width="732" alt="image" src="https://github.com/caravagnalab/CNAqc/assets/15940404/af16ac8d-257f-4957-b8ed-e0b8c56fe424">

**Comment by caravagn** [comment]
Hi, I see your panel D and agree that it should be possible to select the 50% peak. I think it's matter of tuning some peak-detection parameters because usually we work with higher TMB and maybe the default params are not as good for your specific case. 

We can def try to help you find those, but is there any way you can share with us the data from panel D? You can anonimize anything if required (eg., make up nucleotide positions, ref/alt etc).

**Comment by yavorska** [comment]
Hi @caravagn,
That would be great! At least one such sample is available in the research environment (https://www.genomicsengland.co.uk/research/research-environment). If you raise a GEL service desk ticket, I can point you to it, feel free to tag me directly, @Olena Yavorska.

**Comment by caravagn** [comment]
@AliceAntonello can you do open the ticket following @yavorska?

**Comment by AliceAntonello** [comment]
Hi @yavorska, I found the sample you referred to in the research environment, could you share with me the code you used to produce the CNAqc object, so that I follow the same steps as you?

**Comment by yavorska** [comment]
Hi @AliceAntonello, I emailed the details a while back to the account that was used to generate the SD ticket. Can you confirm if you got them?

**Comment by AliceAntonello** [comment]
Hello,

Yes, I confirm I received it. I apologise for the delay in responding to your request, I’ll get back to it as soon as possible.

Sorry again.

**Comment by caravagn** [comment]
Has this been resolved? If yes, @AliceAntonello you should close the issue.

**Comment by AliceAntonello** [comment]
Hi! 

I apologise but I was not able to solve the issue. I tried to tweak some parameters to see if I could change the result, but in this particular case the purity estimate is too off and the input purity too low. I think we would need to try another strategy to address this  issue.

**Comment by caravagn** [comment]
I think in general it is hard to believe that the peak close to `0.5` is actually a clonal peak. If these are WGS samples it seems plausible to find hundreds of clonal mutations, and not `3`.

What tumours were this @yavorska ?

**Comment by yavorska** [comment]
Hi @caravagn, it's an ALL.
