### ISSUE TITLE
Bug in the analyze_peaks function (not recognizing `matching_epsilon = NULL`)

### ISSUE THREAD

**Issue by vvvirgy** [caravagnalab/CNAqc#30]
I am trying to run the example data analysis reported in the [documentation](https://caravagnalab.github.io/CNAqc/articles/a7_example_MSeq.html). After having created the CNAqc object with all the samples downloaded as indicated, I run the function `analyze_peaks`, as follows (`CNAqc_samples` is just a list of CNAqc objects):  

```r
CNAqc_samples_peaks = lapply(CNAqc_samples, function(x) {
  CNAqc::analyze_peaks(x, 
                       purity_error = 0.05, 
                       matching_strategy = 'closest')
})
``` 
My R console enters in debug mode, reporting issue at the row 129 of the `analyze_peaks` function: 
```r
  if (!is.null(matching_epsilon)) {
    stop("matching_epsilon is deprecated - using purity_error = ",
         purity_error)
    matching_epsilon = purity_error
  }
``` 
Although `matching_epsilon = NULL` by default. 

I can make the code move on and execute the analysis anyway until the next breakpoint (which occurs when the function will be run on the next sample), but I don't understand why `matching_epsilon` is recognised as not NULL even if it should be by default. I have also tried to explicity define it as NULL when calling the function, but the issue occurred anyway.

**Comment by caravagn** [comment]
You need a reprex example for me to reproduce it, otherwise it's hard. Ofc, if you fix it yourself happy to check your fix.

**Comment by caravagn** [comment]
Is this still a thing?

**Comment by vvvirgy** [comment]
It seems that is not a problem anymore, probably it was fixed by other adjustments in the latest weeks
