### ISSUE TITLE
Multisample utilities

### ISSUE THREAD

**Issue by vvvirgy** [caravagnalab/CNAqc#31]
Hi everyone. 
me and @nicola-calonaci developed a function (`multisample_init`) that might be useful when analysing different samples from the same patient. It takes as input a named list (names must be present and correspond to the `sample_id`) of CNAqc objects and defines a common segmentation by merging the original breakpoints from all single samples. Mutations are also remapped on the new segments such that analysis of private and shared mutations is straightforward in multisample or longitudinal assays. 

I will upload asap the documented script on my fork of the repository. You might consider it for a pull request.

**Comment by caravagn** [comment]
Updates on this?

**Comment by caravagn** [comment]
Dead.
