### ISSUE TITLE
Warning message after changing `min_absolute_karyotype_mutations`

### ISSUE THREAD

**Issue by mkyriak** [caravagnalab/CNAqc#36]
Hello,

Thank you for the tool. Finally, there is a way to start from SNVs, CNAs and purity and perform QC and check for clonality!

I tried to run `analyze_peaks` command by changing the `min_absolute_karyotype_mutations` parameter since I want to perform the analysis on targeted sequencing data and not on WGS.

This is an instance of the commands I tried (after running `init`).

```
samplePurityTolerance <- auto_tolerance(0.6, 40, fpr=0.1)

sample_analysis <- analyze_peaks(sample_analysis, karyotypes = c("1:0", "1:1", "2:0", "2:1"), purity_error = samplePurityTolerance$epsilon_range, min_absolute_karyotype_mutations=20)
```

However, when I enter a number that is smaller than the total number of SNVs that I detect in my sample, I get the following error:

```
Warning messages:
1: In `[<-.data.frame`(`*tmp*`, ri, , value = list(Purity = 0.02,  :
  provided 2 variables to replace 1 variables
2: In `[<-.data.frame`(`*tmp*`, ri, , value = list(Purity = 0.014,  :
  provided 2 variables to replace 1 variables
3: In `[<-.data.frame`(`*tmp*`, ri, , value = list(Purity = 0.009,  :
  provided 2 variables to replace 1 variables
```

I am not sure what is going on here, could you please help me figure it out?

Thank you in advance!

Maria

**Comment by caravagn** [comment]
Hi, warnings are not errors. Did it compute anything?

**Comment by caravagn** [comment]
@AliceAntonello can you raise a `stop()` error when this happens?

**Comment by AliceAntonello** [comment]
Sure

**Comment by caravagn** [comment]
@AliceAntonello if you pushed the fix can u close this?

**Comment by AliceAntonello** [comment]
I tried to reproduce the problem but I didn't receive any error and the computations went smoothly. Also, a check on the minimum number of mutations per karyotype is already in place.
