### ISSUE TITLE
Request to fix 2 bugs

### ISSUE THREAD

**Issue by Kazuki526** [caravagnalab/CNAqc#37]
Hi, thank you for great tools.
I found two bugs, so please fix them.

1. An error occurs when `supported_peaks = c(“1:0”, “1:1”, “2:0”, “2:1”, “2:2”)` is not present in the karyotype of subclonal CNA.

2. In the function called single_run() within simple_peak_detector(), it occasionally throws an error saying 'Assigned data `hst[round(pks$x * 100)]` must be compatible with existing data.'.
I think that this is probably an error that occurs when peak_algorithms.R line 735 'round(pks$x * 100)' contains a zero.
Therefore, I think that changing line 730 
`dplyr::filter(x <= 1, x >= 0) 
`to
`dplyr::filter(x <= 1, x >0)
` will solve the problem.

**Comment by AliceAntonello** [comment]
Can you also post an example of the code you are using?

**Comment by caravagn** [comment]
Cannot reproduce.

**Comment by Kazuki526** [comment]
Sorry for the delay.
I will upload example data and scripts for errors 1 and 2.
My apologies. For error 2 I may have made a mistake in what I thought was the cause of the error.
[exdata.zip](https://github.com/user-attachments/files/16195732/exdata.zip)

**Comment by caravagn** [comment]
OK we are re-opening and will look into your data (@AliceAntonello )

**Comment by AliceAntonello** [comment]
The two bugs are fixed now, let us know if everything works

**Comment by Kazuki526** [comment]
Thank you very much for your quick help!
