### ISSUE TITLE
Automatically annotate driver and interesting SNVs

### ISSUE THREAD

**Issue by Militeee** [caravagnalab/CNAqc#7]
The idea is to help the user by annotating the snvs table using VEP and ANNOVAR, as well as annotate known drivers.
The best idea is to use an already existing R interface such as [anor]( https://github.com/clindet/anor). 
Development is expected in a new branch called `annovar`

**Comment by caravagn** [comment]
Can we close this? @Militeee

**Comment by Militeee** [comment]
As we now provide a minimum working functionality I would say yes
